# Generated by Django 5.2.3 on 2025-06-21 00:20

import Accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', Accounts.models.CustomUserManager()),
            ],
        ),
    ]
