# Generated by Django 5.2.3 on 2025-06-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='Products.category'),
        ),
    ]
